### ISSUE TITLE
Colors not recognized

### ISSUE THREAD

**Issue by gitLabor8** [timjs/elm-collage#1]
Colors do not seemed to be included in your library.
I have tried multiple different colors and even the function `rgb`, but none of them gets recognized.

```
Cannot find variable Collage.red.

50|       |> filled (uniform Collage.red )
                             ^^^^^^^^^^^
Collage does not expose red. 

```

**Comment by timjs** [comment]
Hi @gitLabor8,

Please use the colors defined in the Elm `Color` module. It will solve your problem.
