### ISSUE TITLE
Outlined Polygon is not auto-closed

### ISSUE THREAD

**Issue by timting** [timjs/elm-collage#26]
The documentation states that Polygon will auto-close all shapes; however when I was outlining a polygon today, it only traced the line segments which were defined by the list of tuples and didn't auto-close it. I'm new to Elm and Collage - is this expected behavior?

**Comment by timjs** [comment]
Hi @timting!

Sorry for my slow reaction. Can you send me a small example? The code below works for me:

```elm
w = 100

points =
    [ ( 0, 20 )
    , ( -20, 0 )
    , ( 0, -20 )
    , ( w, -20 )
    , ( w + 20, 0 )
    , ( w, 20 )
    ]

shape =
    polygon points
        |> styled
            ( uniform Color.red
            , solid thin (uniform Color.black)
            )
        |> center
```

**Comment by timting** [comment]
```
---- MODEL ----


type alias Model =
    { shape : Collage.Shape
    }


init : ( Model, Cmd Msg )
init =
    ( { shape = Collage.polygon [ ( 15, 15 ), ( 0, 15 ), ( 0, 0 ) ]
      }
    , Cmd.none
    )



---- UPDATE ----


type Msg
    = NoOp


update : Msg -> Model -> ( Model, Cmd Msg )
update msg model =
    ( model, Cmd.none )



---- VIEW ----


view : Model -> Html Msg
view model =
    div []
        [ svg (Collage.outlined Collage.defaultLineStyle model.shape)
        ]



---- PROGRAM ----


main : Program Never Model Msg
main =
    Html.program
        { view = view
        , init = init
        , update = update
        , subscriptions = always Sub.none
        }
```

is what I have. Now that I understand how things work better, I think what is happening is the the svg command is creating too tight a viewbox for the triangle, so it's clipping one edge. This works fine with the svgBox command with a larger box.

Thanks for the reply, and no problem on the delay - life's busy!
